export default {
    mainMenu: {
      title: 'Fanorona',
      subtitle: 'Jeu de Stratégie Traditionnel Malgache',
      playLocal: 'Jouer en Local',
      playVsAI: 'Jouer contre IA',
      playOnline: 'Jouer en Ligne',
      tutorials: 'Tutoriels',
      rules: 'Règles',
      profile: 'Profil',
      settings: 'Paramètres',
      community: 'Communauté',
    },
    gameModes: {
      local: 'Partie Locale',
      ai: 'contre Ordinateur',
      online: 'Match en Ligne',
    },
    aiDifficulty: {
      beginner: 'Débutant',
      intermediate: 'Intermédiaire',
      master: 'Maître',
    },
    game: {
      whiteTurn: 'Tour des Blancs',
      blackTurn: 'Tour des Noirs',
      thinking: "L'IA réfléchit...",
      captureChain: 'Continuer les captures ou finir le tour',
      endChain: 'Finir la Chaîne',
      draw: 'Proposer Nulle',
      resign: 'Abandonner',
      undo: 'Annuler',
      pause: 'Pause',
      whiteCaptured: 'Blancs Capturés',
      blackCaptured: 'Noirs Capturés',
    },
    gameEnd: {
      whiteWins: 'Les Blancs Gagnent!',
      blackWins: 'Les Noirs Gagnent!',
      draw: 'Match Nul',
      rematch: 'Revanche',
      mainMenu: 'Menu Principal',
      analyze: 'Analyser',
    },
    settings: {
      title: 'Paramètres',
      theme: 'Thème',
      language: 'Langue',
      sound: 'Effets Sonores',
      music: 'Musique',
      vibration: 'Vibration',
      showHints: 'Afficher les Indices',
      autoQueen: 'Auto-Reine',
      confirmMoves: 'Confirmer les Coups',
    },
    profile: {
      title: 'Profil',
      gamesPlayed: 'Parties Jouées',
      wins: 'Victoires',
      losses: 'Défaites',
      draws: 'Nuls',
      winRate: 'Taux de Victoire',
      voninahitra: 'Classement Voninahitra',
      achievements: 'Succès',
    },
    tutorials: {
      title: 'Apprendre Fanorona',
      basics: 'Règles de Base',
      captures: 'Capturer des Pièces',
      advanced: 'Tactiques Avancées',
      practice: 'Problèmes Pratiques',
    },
    common: {
      ok: 'OK',
      cancel: 'Annuler',
      yes: 'Oui',
      no: 'Non',
      back: 'Retour',
      next: 'Suivant',
      continue: 'Continuer',
      start: 'Commencer',
      loading: 'Chargement...',
      error: 'Erreur',
    },
  };