export default {
    mainMenu: {
      title: 'Fanorona',
      subtitle: 'Lalao Tetika Nentim-paharazana Malagasy',
      playLocal: 'Lalao Eto',
      playVsAI: 'Lalao amin\'ny AI',
      playOnline: 'Lalao an-tserasera',
      tutorials: 'Fampianarana',
      rules: 'Fitsipika',
      profile: 'Mombamomba',
      settings: 'Fandrindrana',
      community: 'Vondrom-piarahamonina',
    },
    gameModes: {
      local: 'Lalao Eto',
      ai: 'amin\'ny Solosaina',
      online: 'Lalao an-tserasera',
    },
    aiDifficulty: {
      beginner: 'Vao Manomboka',
      intermediate: 'Antonony',
      master: 'Mahay',
    },
    game: {
      whiteTurn: 'Andian\'ny Fotsy',
      blackTurn: 'Andian\'ny Mainty',
      thinking: 'Misaina ny AI...',
      captureChain: 'Tohizo ny fisamborana na farany',
      endChain: 'Farany',
      draw: 'Manolotra Tsy Resy',
      resign: 'Mihemotra',
      undo: 'Avereno',
      pause: 'Ajanony',
      whiteCaptured: 'Fotsy Voasambotra',
      blackCaptured: 'Mainty Voasambotra',
    },
    gameEnd: {
      whiteWins: 'Fotsy no Mandresy!',
      blackWins: 'Mainty no Mandresy!',
      draw: 'Tsy Resy',
      rematch: 'Averina',
      mainMenu: 'Menu Fototra',
      analyze: 'Analisao',
    },
    settings: {
      title: 'Fandrindrana',
      theme: 'Loko',
      language: 'Fiteny',
      sound: 'Feo',
      music: 'Mozika',
      vibration: 'Fihovitrovitra',
      showHints: 'Asehoy ny Tolo-kevitra',
      autoQueen: 'Auto-Mpanjakavavy',
      confirmMoves: 'Hamarino ny Fiketsahana',
    },
    profile: {
      title: 'Mombamomba',
      gamesPlayed: 'Lalao Vita',
      wins: 'Fandresena',
      losses: 'Faharesena',
      draws: 'Tsy Resy',
      winRate: 'Tahan\'ny Fandresena',
      voninahitra: 'Naoty Voninahitra',
      achievements: 'Zava-bita',
    },
    tutorials: {
      title: 'Mianara Fanorona',
      basics: 'Fitsipika Fototra',
      captures: 'Fisamborana',
      advanced: 'Paikady Avo lenta',
      practice: 'Fanazaran-tena',
    },
    common: {
      ok: 'OK',
      cancel: 'Aoka ihany',
      yes: 'Eny',
      no: 'Tsia',
      back: 'Miverina',
      next: 'Manaraka',
      continue: 'Tohizo',
      start: 'Atombohy',
      loading: 'Mamaky...',
      error: 'Tsy fetezana',
    },
  };